/* DO NOT EDIT THIS FILE - it is machine generated */
//#include <jni.h>
/* Header for class javajnetest_XitLibJNE */

//#ifndef _Included_javajnetest_XitLibJNE
//#define _Included_javajnetest_XitLibJNE
#ifdef __cplusplus
extern "C" {
#endif
int giveIntGetInt();
//JNIEXPORT jint JNICALL Java_javajnetest_XitLibJNE_intMethod
//  (JNIEnv *, jobject, jint);
//
///*
// * Class:     javajnetest_XitLibJNE
// * Method:    booleanMethod
// * Signature: (Z)Z
// */
//JNIEXPORT jboolean JNICALL Java_javajnetest_XitLibJNE_booleanMethod
//  (JNIEnv *, jobject, jboolean);
//
///*
// * Class:     javajnetest_XitLibJNE
// * Method:    stringMethod
// * Signature: (Ljava/lang/String;)Ljava/lang/String;
// */
//JNIEXPORT jstring JNICALL Java_javajnetest_XitLibJNE_stringMethod
//  (JNIEnv *, jobject, jstring);
//
///*
// * Class:     javajnetest_XitLibJNE
// * Method:    intArrayMethod
// * Signature: ([I)I
// */
//JNIEXPORT jint JNICALL Java_javajnetest_XitLibJNE_intArrayMethod
//  (JNIEnv *, jobject, jintArray);

#ifdef __cplusplus
}
#endif
//#endif
